### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#1]
Please add guide how to install on fresh ubuntu 14,15 or debian 7,8.

**Comment by SlvrEagle23** [comment]
Although installation is only currently supported on Ubuntu 14.04 and 16.04, installation instructions for both have been uploaded to [the wiki page](https://github.com/SlvrEagle23/AzuraCast/wiki/Deploying-to-an-Existing-Server).

**Comment by jbenz** [comment]
Are there still debian install instructions available?

**Comment by lovefmhits** [comment]
bonjour  je vien  install  shoutcast  dans azurcast  mais  j ai un message 
502 Bad Gateway
nginx j ai redemarre  le server  mais j ai  toujour  le meme message 
je ne vois pas crois faire  merci  de  pour tout info  sur  install

**Comment by fcardenas886** [comment]
quise instalar la ultima version en debian y ubuntu y no pude me da error 
![Captura azura](https://user-images.githubusercontent.com/88418753/128584943-09dc0002-6993-42c8-b2f0-ca6e84b7cc6d.JPG)
nose si me pueden ayudar como seguir con la instalacion
