### ISSUE TITLE
user permission

### ISSUE THREAD

**Issue by athensguy** [SlvrEagle23/AzuraCast#100]
When you assign station permission to user it does not work at all and no access to manage and control station nor autodj for station

**Comment by SlvrEagle23** [comment]
@athensguy I'm not seeing this error on my end...can you explain in more detail please?

If you're the station administrator, you should be able to log in as the other user and verify their permissions work correctly. I am happy to look into any specific pages or permissions that aren't working as expected.

**Comment by athensguy** [comment]
That's what I am doing:

- Using main administrator account, I can create TestStation as Shoutcast2 station
- Using Users > permissions, I managed to add new permission as below 

Role Name: StationManager
System-Wide Permissions: blank (No actions)
TestStation: assigned everything (All actions available)

- Using Users > User accounts, I added new user and set his role StationManager

When I login with user that has StationManager role, he can view stats and modify his account, choose theme for AzuraCast while no manage button for station. When attempt to access manage station url directly, I got alert reporting access is denied.

**Comment by SlvrEagle23** [comment]
@athensguy Thank you very much for the detailed reproduction...I see exactly what the problem is, will be pushing a fix up ASAP for it.
