### ISSUE TITLE
Terminating Station is not terminating service

### ISSUE THREAD

**Issue by athensguy** [SlvrEagle23/AzuraCast#105]
When you create a radio station and decide to remove it, script remove it from database while if you run top command, you will be able to see that radio station is still running and using port. Media files and all configuration folders/files remain as its.

**Comment by SlvrEagle23** [comment]
@athensguy Another excellent catch and a definitely valid issue; after the switch to using supervisord to run all station processes, the station deletion wasn't updated to remove the configuration that would keep the station processes from coming back anyway. This has been fixed. :)
