### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#2]
please add screenshots from panel inside etc.

**Comment by SlvrEagle23** [comment]
Hello! I definitely will add all the regular features associated with a software package (screenshots, download and installation instructions, etc.) once the core functionality of the app is finished. Right now, it's in a super-early development process where the features and functionality are still in flux too much to make installation instructions or screenshots useful just yet.

**Comment by efsysefsys** [comment]
ok thanks

**Comment by SlvrEagle23** [comment]
Screenshots have been posted to the [wiki page](https://github.com/SlvrEagle23/AzuraCast/wiki/Screenshotsl)!
