### ISSUE TITLE
500

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#33]
now i try again install on ubuntu 16 all done but when i open http://myip.com i see

500
Named route does not exist for name: setup:index
/var/azuracast/www/vendor/slim/slim/Slim/Router.php : 258

**Comment by SlvrEagle23** [comment]
Hello and thank you for the report. Issues with setup should now be fixed, just run `chmod a+x update.sh` and `./update.sh` on your installation to pull down the new changes.

**Comment by isaiaswebnet** [comment]
How can I fix this bug? When you delete a music request.

500 A 
Named route does not exist for name: stations:requests:index
Router.php : 279
![sem titulo-1](https://user-images.githubusercontent.com/4692453/49333568-36f2e900-f5a8-11e8-862b-d41475936277.jpg)
