### ISSUE TITLE
"Syntax Error while loading YAML." on install

### ISSUE THREAD

**Issue by mkody** [SlvrEagle23/AzuraCast#34]
Tried to spin this on a C1 server at Scaleway (4 ARMv7 cores, 2GB RAM, 50GB LSSD) with Ubuntu 16.04.

Just after `Installing AzuraCast (Environment: production)` appears, I get this error:
![1474304870](https://cloud.githubusercontent.com/assets/843787/18641312/60ca4078-7e9c-11e6-9997-b7a8f8a11acb.png)

And the file content...
```
---
- name: send user notification
  debug:
    msg: "A user account named 'azuracast' has been created. The password associated with this account is: {{ azuracast_user_password }}"
S
```

**(yes, the "S" here too)**

Full install log here: https://gist.github.com/mkody/61bc1ff0207002d5262fe54d8c4cacf3

**Comment by SlvrEagle23** [comment]
Hahah @mkody you picked the exact worst time to spin up a server on AzuraCast :P

I *just* pushed up a fix, do `git reset --hard && git pull` then `chmod a+x install.sh` and `./install.sh` again to fix it.
