### ISSUE TITLE
Expand Playlist Support to Include Regular (Current), Scheduled, Once Per X Songs, Once Per Day

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#38]
Very well be if they could set the playlist during playback.  ( set day, time , playlist )+ shuffle mode or normal and add radio jingles section.If need i have some liquidsoap config examples.

#playlists
day     = mksafe(audio_to_stereo(playlist(reload=3600,"/home/liquidsoap/playlists/day/")))
night   = mksafe(audio_to_stereo(playlist(reload=3600,"/home/liquidsoap/playlists/night/")))

myplaylist = switch([({7h-12h}, morning), ({12h-18h}, afternoon), ({18h-24h}, evening), ({0h-7h}, night)])
radio = myplaylist

jingles = mksafe(audio_to_stereo(playlist(reload=3600, '/home/liquidsoap/playlists/jingles/')))
clock = audio_to_stereo(single("/home/liquidsoap/clock/clock.ogg"))

radio = random(weights = [1, 4],[jingles, radio])
radio = add([radio, switch([({0m0s},clock)])])
radio = crossfade(start_next=6.0, fade_out=3.0, fade_in=3.0, radio)
radio = mksafe(fallback(track_sensitive=false, [live, radio]))

## p.s.

for live dj use icecast falback its not good idea! listeners have disconnect and reconnect etc ! beter use liquidsoap function **Harbor input + crossfade** ! if u need? i have exemplaes :)

+ maby u can add rename or edit files function in Music File Manager.Sometime people need rename files :)

**Comment by mkody** [comment]
+1 for this issue, I talked with Silver about this yesterday.

<hr>

> for live dj use icecast falback its not good idea! listeners have disconnect and reconnect etc !

That's weird. My webradio has been using Icecast and fallbacks for a long time and listeners don't [dis|re]connect. But yeah,Liquidsoap (+ crossfade 😉) might be better.

**Comment by efsysefsys** [comment]
with falback server play sound when dj connect on moment diferent song:)  but with harbor the song remains the quietest and gently move to a new dj song.its beter like a pro :P :) falback is old system for home not for serious project.
