### ISSUE TITLE
Evaluate Support for ShoutCast2

### ISSUE THREAD

**Issue by SlvrEagle23** [SlvrEagle23/AzuraCast#4]

**Comment by SlvrEagle23** [comment]
Looking into support for Shoutcast 2, there are a few issues that I am running into:

 - No URL-based authentication for streamer accounts
 - Unsure about requirement to be listed in YP2 (or to at least have a YP2 authhash)
 - Need to purchase and apply a license key for MP3 audio to be broadcast through ShoutCast

If anyone can shed any light onto these issues and provide potential resolution, it would be greatly appreciated. In the meantime, I feel like IceCast is, far and away, the more configurable and flexible option for handling radio streaming.

**Comment by efsysefsys** [comment]
shoutcast is bad :) old & death :) if someone need i can give license code to test :) icecast best way
