### ISSUE TITLE
Add in-site editing for Station Media, including writing modified ID3 info back to the source file

### ISSUE THREAD

**Issue by mkody** [SlvrEagle23/AzuraCast#41]
Sometimes you upload a file and there's a mistake with the tags (or they're missing).
[I saw there's a `writeSongData` here](https://github.com/SlvrEagle23/AzuraCast/blob/469a727e6457fa7a45865d255c295aa21488b32e/app/library/App/Sync/Media.php#L147), any progress on this?

**Comment by efsysefsys** [comment]
I agree +1

**Comment by SlvrEagle23** [comment]
Going to rephrase this one, as it's definitely something I've wanted to add into the system.
