### ISSUE TITLE
start,stop,restart

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#43]
need start, stop, restart buttons on `station/id/profile`
sometime need stop or start liquidsoap or icecast.

**Comment by mkody** [comment]
Why would you want to start/stop? And for start, the "Restart" works fine.

**Comment by efsysefsys** [comment]
maybe people need manual edit liquidsoap conf or recompile or etc. stop.start not bad function stop start for icecats and same for liquidsoap.

**Comment by SlvrEagle23** [comment]
I'm not so sure that these functions need to be separated out, as "restart" is already available for both the liquidsoap backend and icecast frontend individually, and "restart" implies taking the radio from any state it's currently in (stopped or running) to running with reloaded configuration, which is usually the desired outcome.

**Comment by efsysefsys** [comment]
ok  and if i do ./update.sh i dont need stop icecast , liquidsoap servers?No error logs etc ?
