### ISSUE TITLE
Music file manager bug

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#44]
I make update today , if i try upload more then 10 music files at one time. Files not show and always loading.I go with sftp on my server & i see files uploaded hmm.

![fmbug](https://cloud.githubusercontent.com/assets/17949473/18708641/9eb997a8-8004-11e6-89b1-2373370eb1ba.png)

## update

file manager broken if files have russian or other charset name.If i upload song with russian laters file manager dont show files.

**if i upload song like that.**
Dj Bambam - Дыхание одно на двоих (remix).mp3

file manager dont show any files.

**Comment by SlvrEagle23** [comment]
Can you e-mail me that file so I can test with it locally?

**Comment by efsysefsys** [comment]
ok

**Comment by SlvrEagle23** [comment]
Thank you for the demo file! It turns out filenames with UTF-8 encoding that were longer than the threshold which would normally add "..." to shorten the file name caused an error, as PHP's native `substr` doesn't handle multibyte strings correctly. Switching to mb_substr works fine. :)
