### ISSUE TITLE
Set default playlist per folder?

### ISSUE THREAD

**Issue by mkody** [SlvrEagle23/AzuraCast#46]
When I upload new content, I need to select and add them to the playlist.
The thing is, I like to organize stuff a bit, so I put every playlist or type of content in different folders.
```
media/
├── Jingles
└── Lecture
```
Now, I always put everything that's inside `Lecture` in the same playlist, but selecting new songs and adding them to the playlist takes more and more time. Selecting one after another is slow and selecting "All" take **a lot of time** with more than 100 songs inside the folder.
But note that the content of `Jingles` aren't sharing the same playlist, they're individually selected.

I'd like to suggest a "default playlist" when we upload new content to a specified folder.

**Comment by SlvrEagle23** [comment]
The latest commit may address the issue you're referring to without needing the major database changes that having folders that auto-assign to playlists would be.

Now you can select a folder in a parent directory, and "clear playlists", "add playlists" and "delete" actions will automatically cascade down to _all_ files in the directory. This lets you add an entire directory to a playlist in a single step.

**Comment by SlvrEagle23** [comment]
4495cac Should fix any performance issues associated with this...there was a minor typo in the code (if the filemtime was *equal* to the stored one, it would reprocess the file) causing every file being processed to be reloaded from the ID3 tags on the filesystem, unnecessarily.

**Comment by SlvrEagle23** [comment]
Closing this issue as recent commits have fixed issues relating to selecting a folder in the parent directory and playlist changes applying to the entire folder, which achieves the same purpose without intrusion into the database schema.
