### ISSUE TITLE
Evaluate adding support for additional output encoders (Ogg Vorbis, AAC, Opus, etc)

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#47]
I think good idea if users can add more encoders like ogg and aac+ or opus. + set bitrate.

p.s. aac+ very nice if radiostation  have mobile apk.

(liquidsoap outputs)

**Comment by efsysefsys** [comment]
u know opus dont show metadata? on icecast never show current artist and song name.people get this info from liquidsoap and serve to php scripts or panels.Buts its trifle.if u make add encoders function please add fields where users can change description, genere, radio url ,etc info.

my old manual liquidsoap config example.

#stream output to icecast2 server.

```
output.icecast(%mp3(stereo=true, samplerate=44100, bitrate=128, id3v2=true),
        icy_metadata="true",
        mount = "/radio",
        host = "127.0.0.1", port = 8000, password = "myponny123",
        genre = "city, urban, dance, , various",
        description = "my internet radio",
        name = "my radio mp3 128kbp\s 44khz",
        url = "http://mysite.com", radio)
```

very good if fields like description, url ,genere, can be edit.drom panel

**Comment by mkody** [comment]
>station listing in icecast dir

Well, maybe as an option in the station config. But **don't** add it by default.

**Comment by efsysefsys** [comment]
& if add encoders function only liquidsoap harbor in good :) shit fallback go away:P because how u make fallback on diferent format? only profesional harbor :P :) fallback for amature,
