### ISSUE TITLE
LiquidSoap appears "offline" and seems to crash at each songs

### ISSUE THREAD

**Issue by mkody** [SlvrEagle23/AzuraCast#48]
The station profile says that LiquidSoap is not running. Which isn't true since I can listen to my music.
![2016-09-22_091839](https://cloud.githubusercontent.com/assets/843787/18739684/9445070c-80a5-11e6-92d9-f987649f9d5c.png)

Also, when taking a look at the LiquidSoap logs for the station, it looks like it crashes.
`2016/09/22 07:12:25 [radio_out:2] Error while sending data: could not write data to host: Broken pipe in write()!`
[Here's a snippet of my liquidsoap logs. ](https://gist.github.com/mkody/b04a6edc35c810af4d04c16038e0ff63)

**Comment by SlvrEagle23** [comment]
Closed as an issue related to a zombie process on this particular installation.

If you're seeing this issue on your own AzuraCast installation, a quick `sudo killall -9 liquidsoap` in the terminal as a SU-capable user (or root) should remove any "zombie" processes that are hanging around. You can then restart the radio service from the web console.
