### ISSUE TITLE
You have playlists configured, but none are set as

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#50]
when i make update.sh 

console log :

`TASK [azuracast-update : Restart Radio Stations] *******************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php radio:restart", "delta": "0:00:00.424183", "end": "2016-09-29 04:28:30.487460", "failed": true, "rc": 1, "start": "2016-09-29 04:28:30.063277", "stderr": "\n                                                                                                                                                                                           \n  [App\\Exception]                                                                                                                                                                          \n  You have playlists configured, but none are set as \"Default\" type. You need at least one default playlist, so the AutoDJ has something to play when scheduled playlists are not active.  \n                                                                                                                                                                                           \n\nradio:restart", "stdout": "Restarting all radio stations...\n---------------------------------------------\nRestarting station #1: emka.lv", "stdout_lines": ["Restarting all radio stations...", "---------------------------------------------", "Restarting station #1: emka.lv"], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @util/ansible/update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=10   changed=6    unreachable=0    failed=1

root@emka:/var/azuracast/www#

and when i login to panel i see icecast and liquidsoap , red i pres start and all ok hmm
`

**Comment by SlvrEagle23** [comment]
Latest code push should help with this, it downgrades the LiquidSoap playlist issue from an exception to a warning printed out.

**Comment by efsysefsys** [comment]
now all ok :) 

localhost                  : ok=26   changed=10   unreachable=0    failed=0

👍

**Comment by SlvrEagle23** [comment]
yay closing :D
