### ISSUE TITLE
Allow Mount Points to be Customized

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#52]
Where i can change mounts names? I dont like /autodj.mp3 :) i like /stream or /mystation_aac , /mystation_mp3 ( because i manual try add encoders + harbor) or another name but without .mp3.Where i can change manual ? in station config dir ? liq and icecast conf?

p.s. if azuracast have multi language i can translate to russian language.

**Comment by mkody** [comment]
For the translations: https://crowdin.com/project/azuracast

**Comment by Just-In-Web** [comment]
You can change it in /var/azuracast/www/app/library/App/Radio/Frontend/IceCast.php
But only for all. If you've more than one stations this config will be applied for all stations. Only replace autodj.mp3 or radio.mp3 with your name.

**Comment by SlvrEagle23** [comment]
Also, any changes to that file will be overwritten in future updates. I still have plans to integrate this into the web panel to make it editable by users.
