### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#53]
**install on fresh ubuntu 16.04 x64 get errors**

log : 
`Installing AzuraCast (Environment: production)

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [init : debug] ************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04"
}

TASK [init : Update apt] *******************************************************
ok: [localhost]

TASK [init : Install system packages] ******************************************
changed: [localhost] => (item=[u'apt-transport-https', u'curl', u'wget', u'build-essential', u'python-software-properties', u'pwgen', u'whois'])

TASK [python : Add key for ppa python repository] ******************************
skipping: [localhost]

TASK [python : Add ppa python repository] **************************************
skipping: [localhost]

TASK [python : Update apt] *****************************************************
skipping: [localhost]

TASK [python : Ensure python2.7 latest is installed] ***************************
skipping: [localhost]

TASK [python : fail] ***********************************************************
skipping: [localhost]

TASK [git : Install Git] *******************************************************
ok: [localhost]

TASK [azuracast-radio : Install IceCast2 (14.04)] ******************************
skipping: [localhost]

TASK [azuracast-radio : Install IceCast2 (16.04)] ******************************
changed: [localhost]

TASK [azuracast-radio : Install LiquidSoap] ************************************
changed: [localhost] => (item=[u'liquidsoap', u'liquidsoap-plugin-all'])

TASK [azuracast-radio : Link Fallback Error MP3] *******************************
changed: [localhost]

TASK [azuracast-user : (Prod) Generate AzuraCast Password] *********************
changed: [localhost]

TASK [azuracast-user : Create Groups] ******************************************
ok: [localhost] => (item=www-data)
ok: [localhost] => (item=admin)

TASK [azuracast-user : Assign User Password] ***********************************
ok: [localhost]

TASK [azuracast-user : Create AzuraCast User] **********************************
changed: [localhost]

TASK [azuracast-user : Modify www-data User] ***********************************
changed: [localhost]

TASK [azuracast-user : (Dev) Modify vagrant User] ******************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Modify www-data User] *****************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Add azuracast User to vagrant Group] **************
skipping: [localhost]

TASK [azuracast-config : Use Default Configuration Files] **********************
changed: [localhost] => (item=db)
changed: [localhost] => (item=influx)
changed: [localhost] => (item=cache)

TASK [azuracast-config : Write current environment to file.] *******************
changed: [localhost]

TASK [azuracast-config : Touch .deploy_run file] *******************************
changed: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] *******************
changed: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Create System Folders] ********************************
changed: [localhost] => (item=/var/azuracast/www_tmp)
changed: [localhost] => (item=/var/azuracast/www_tmp/cache)
changed: [localhost] => (item=/var/azuracast/www_tmp/sessions)
changed: [localhost] => (item=/var/azuracast/www_tmp/proxies)
changed: [localhost] => (item=/var/azuracast/stations)

TASK [influxdb : Add InfluxDB repo file] ***************************************
changed: [localhost]

TASK [influxdb : Add InfluxDB repo key] ****************************************
changed: [localhost]

TASK [influxdb : Update apt cache] *********************************************
ok: [localhost]

TASK [influxdb : Install InfluxDB] *********************************************
changed: [localhost] => (item=[u'influxdb'])

TASK [influxdb : restart influxdb] *********************************************
changed: [localhost]

TASK [influxdb : Set up Initial InfluxDB Database] *****************************
changed: [localhost] => (item=CREATE DATABASE "stations";)
changed: [localhost] => (item=CREATE RETENTION POLICY "15s" ON "stations" DURATION 5d REPLICATION 1 DEFAULT;)
changed: [localhost] => (item=CREATE RETENTION POLICY "1h" ON "stations" DURATION 2w REPLICATION 1;)
changed: [localhost] => (item=CREATE RETENTION POLICY "1d" ON "stations" DURATION INF REPLICATION 1;)
changed: [localhost] => (item=CREATE CONTINUOUS QUERY "cq_1h" ON "stations" RESAMPLE EVERY 30m FOR 6h BEGIN SELECT min(value) AS min, mean(value) AS value, max(value) AS max INTO "1h".:MEASUREMENT FROM /.*/ GROUP BY time(1h) END;)
changed: [localhost] => (item=CREATE CONTINUOUS QUERY "cq_1d" ON "stations" RESAMPLE EVERY 6h FOR 2d BEGIN SELECT min(value) AS min, mean(value) AS value, max(value) AS max INTO "1d".:MEASUREMENT FROM /.*/ GROUP BY time(1d) END;)

TASK [influxdb : Update InfluxDB] **********************************************
skipping: [localhost] => (item=ALTER RETENTION POLICY "15s" ON "stations" DURATION 5d REPLICATION 1 DEFAULT;)
skipping: [localhost] => (item=ALTER RETENTION POLICY "1h" ON "stations" DURATION 2w REPLICATION 1;)
skipping: [localhost] => (item=ALTER RETENTION POLICY "1d" ON "stations" DURATION INF REPLICATION 1;)
skipping: [localhost] => (item=DROP CONTINUOUS QUERY "cq_1h" ON "stations";)
skipping: [localhost] => (item=DROP CONTINUOUS QUERY "cq_1d" ON "stations";)
skipping: [localhost] => (item=CREATE CONTINUOUS QUERY "cq_1h" ON "stations" RESAMPLE EVERY 30m FOR 6h BEGIN SELECT min(value) AS min, mean(value) AS value, max(value) AS max INTO "1h".:MEASUREMENT FROM /.*/ GROUP BY time(1h) END;)
skipping: [localhost] => (item=CREATE CONTINUOUS QUERY "cq_1d" ON "stations" RESAMPLE EVERY 6h FOR 2d BEGIN SELECT min(value) AS min, mean(value) AS value, max(value) AS max INTO "1d".:MEASUREMENT FROM /.*/ GROUP BY time(1d) END;)

TASK [influxdb : Lock down InfluxDB to localhost requests] *********************
changed: [localhost]

TASK [nginx : Install nginx] ***************************************************
changed: [localhost]

TASK [nginx : Change default nginx site] ***************************************
changed: [localhost]

TASK [nginx : Turn sendfile off on nginx for local development] ****************
skipping: [localhost]

TASK [php : Add PHP PPA repository] ********************************************
skipping: [localhost]

TASK [php : Update apt again] **************************************************
skipping: [localhost]

TASK [php : Install PHP Libraries] *********************************************
changed: [localhost] => (item=[u'php7.0-fpm', u'php7.0-cli', u'php7.0-gd', u'php7.0-curl', u'php7.0-xml', u'php7.0-zip', u'php7.0-intl'])

TASK [php : Create Locales] ****************************************************
changed: [localhost] => (item=de_DE.UTF-8)
changed: [localhost] => (item=es_ES.UTF-8)
changed: [localhost] => (item=fr_FR.UTF-8)
changed: [localhost] => (item=ru_RU.UTF-8)

TASK [php : Remove Old PHP Libraries] ******************************************
ok: [localhost] => (item=[u'php5-common', u'php5-fpm', u'php5-cli', u'php5-phalcon', u'php7.0-phalcon'])

TASK [php : Configure PHP FPM Pool] ********************************************
changed: [localhost]

TASK [php : Configure php-fpm php.ini] *****************************************
changed: [localhost] => (item={u'option': u'post_max_size', u'value': u'50M'})
changed: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})
changed: [localhost] => (item={u'option': u'upload_max_filesize', u'value': u'25M'})

TASK [php : Configure php-cli php.ini] *****************************************
changed: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})

TASK [mariadb : (Prod) Generate MySQL Root Password] ***************************
changed: [localhost]

TASK [mariadb : Assign User Password] ******************************************
ok: [localhost]

TASK [mariadb : Add repo file] *************************************************
skipping: [localhost]

TASK [mariadb : Add repo key] **************************************************
skipping: [localhost]

TASK [mariadb : Update apt cache] **********************************************
skipping: [localhost]

TASK [mariadb : Unattended package installation] *******************************
ok: [localhost]

TASK [mariadb : Install MariaDB] ***********************************************
changed: [localhost] => (item=[u'mariadb-server', u'mariadb-client'])

TASK [mariadb : Add configuration] *********************************************
changed: [localhost]

TASK [mariadb : Start and enable service] **************************************
ok: [localhost]

TASK [mariadb : MySQL Root Account Fix (Ubuntu 16.04)] *************************
changed: [localhost]

TASK [mariadb : Set root Password] *********************************************
changed: [localhost]

TASK [mariadb : Add .my.cnf] ***************************************************
changed: [localhost]

TASK [mariadb : Remove anonymous users] ****************************************
ok: [localhost] => (item=DELETE FROM mysql.user WHERE User='')

TASK [mariadb : Disallow root login remotely] **********************************
ok: [localhost] => (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1'))

TASK [mariadb : Remove test database and access to it] *************************
failed: [localhost] (item=DROP DATABASE test) => {"changed": false, "cmd": ["mysql", "-ne", "DROP DATABASE test"], "delta": "0:00:00.008881", "end": "2016-10-03 09:51:25.044574", "failed": true, "item": "DROP DATABASE test", "rc": 1, "start": "2016-10-03 09:51:25.035693", "stderr": "ERROR 1008 (HY000) at line 1: Can't drop database 'test'; database doesn't exist", "stdout": "", "stdout_lines": [], "warnings": []}
ok: [localhost] => (item=DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%')
...ignoring

TASK [mariadb : Reload privilege tables] ***************************************
ok: [localhost] => (item=FLUSH PRIVILEGES)

TASK [mariadb : Create MySQL Database] *****************************************
changed: [localhost]

TASK [mariadb : Copy default DB config again] **********************************
ok: [localhost]

TASK [mariadb : Set MySQL Password in Application] *****************************
changed: [localhost]

TASK [composer : Install Composer] *********************************************
changed: [localhost]

TASK [composer : Install Composer Dependencies (Development)] ******************
skipping: [localhost]

TASK [composer : Install Composer Dependencies (Production)] *******************
changed: [localhost]

TASK [azuracast-db : Clear AzuraCast Cache] ************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php cache:clear", "delta": "0:00:00.119871", "end": "2016-10-03 09:52:15.638972", "failed": true, "rc": 255, "start": "2016-10-03 09:52:15.519101", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [azuracast-user : send user notification] **********************

RUNNING HANDLER [influxdb : restart influxdb] **********************************

RUNNING HANDLER [nginx : restart nginx] ****************************************

RUNNING HANDLER [php : restart php-fpm] ****************************************

RUNNING HANDLER [mariadb : restart mysql] **************************************

RUNNING HANDLER [mariadb : send mysql notification] ****************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=51   changed=35   unreachable=0    failed=1`

**Comment by SlvrEagle23** [comment]
This should be fixed. Try it again and confirm just to make sure.

**Comment by efsysefsys** [comment]
try again on fresh ubuntu droplet install azuracast. Now i have this error

`Installing AzuraCast (Environment: production)
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes: pkg="{{ item }} state=latest

The error appears to have been in '/var/azuracast/www/util/ansible/roles/azuracast-build/tasks/main.yml': line 34, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: Install Developer Tools
    ^ here

root@emka:/var/azuracast/www#
`

**Comment by efsysefsys** [comment]
after your fix now all ok :)

**Comment by SlvrEagle23** [comment]
:D
