### ISSUE TITLE
error

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#54]
**when i open some pages i see this error, its ok?**
![error](https://cloud.githubusercontent.com/assets/17949473/19065597/0e83f660-8a1d-11e6-87ef-fdbb94f9fd12.png)

**Comment by SlvrEagle23** [comment]
This isn't actually an error, just a rather confusing way of LiquidSoap saying that it has no configuration file to use, therefore it can't play. This only happens when you haven't set up playlists yet. I've updated the system to log a much more understandable error.
