### ISSUE TITLE
Obsolete code

### ISSUE THREAD

**Issue by andbou** [SlvrEagle23/AzuraCast#56]
Some obsolete code in app/modules/frontend/controllers/SetupController.php (line 51) :

             $action = new \Entity\Action;

            $action->name = 'administer all';

            $action->is_global = true;

            $this->em->persist($action);

(line 62) :

            $rha = new \Entity\RoleHasAction;

            $rha->fromArray($this->em, [

                'role' => $role,

                'action' => $action,

            ]);

            $this->em->persist($rha);

**Comment by SlvrEagle23** [comment]
@andbou Good catch. Thank you for letting me know. :)
