### ISSUE TITLE
install error again

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#57]
again install on fresh ubuntu 16 and get this

`TASK [influxdb : Create 'stations' database] ***********************************
changed: [localhost] => (item=stations)

TASK [influxdb : Create 'stations' retention policies] *************************
failed: [localhost] (item={u'duration': u'5d', u'default': True, u'name': u'15s'}) => {"failed": true, "item": {"default": true, "duration": "5d", "name": "15s"}, "msg": "{\"error\":\"error parsing query: found 15s, expected identifier at line 1, char 25\"}\n"}
failed: [localhost] (item={u'duration': u'2w', u'default': False, u'name': u'1h'}) => {"failed": true, "item": {"default": false, "duration": "2w", "name": "1h"}, "msg": "{\"error\":\"error parsing query: found 1h, expected identifier at line 1, char 25\"}\n"}
failed: [localhost] (item={u'duration': u'INF', u'default': False, u'name': u'1d'}) => {"failed": true, "item": {"default": false, "duration": "INF", "name": "1d"}, "msg": "{\"error\":\"error parsing query: found 1d, expected identifier at line 1, char 25\"}\n"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=24   changed=17   unreachable=0    failed=1
`

**Comment by SlvrEagle23** [comment]
Seems to have to do with the version of the python-influxdb library in use on the machine...this fix resolves the issue locally for me. Try it again and let me know. :)

**Comment by efsysefsys** [comment]
i try again install on fresh ubuntu16 droplet now all ok :)
