### ISSUE TITLE
update.sh error

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#58]
error log"

`Checking for Ansible: install ok installed
Updating AzuraCast (Environment: production)
HEAD is now at cdfd22a (Minor) Use computed property names in gruntfile config a           s node supports this.
remote: Counting objects: 73, done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 73 (delta 22), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (73/73), done.
From https://github.com/SlvrEagle23/AzuraCast
   cdfd22a..c32dc59  master     -> origin/master
Updating cdfd22a..c32dc59
Fast-forward
 .codeclimate.yml                                   |  33 +
 Readme.md                                          |   2 +
 app/bootstrap.php                                  |   3 +
 app/library/App/Mvc/View.php                       |   2 +-
 app/library/App/Radio/AdapterAbstract.php          |  42 +
 app/library/App/Radio/Backend/LiquidSoap.php       |  35 +-
 app/library/App/Radio/Frontend/IceCast.php         |  33 +-
 app/library/App/Utilities.php                      | 566 +------------
 app/models/Entity/Song.php                         |   2 +-
 app/models/Entity/StationRequest.php               |   2 +-
 .../stations/controllers/FilesController.php       |   2 +-
 .../stations/controllers/IndexController.php       |   2 +-
 .../views/scripts/reports/duplicates.phtml         |   2 +-
 composer.json                                      |   3 +-
 composer.lock                                      |  43 +-
 web/static/js/app.js                               | 901 +++------------------
 web/static/js/app.min.js                           |   2 +-
 web/static/js/functions.js                         | 705 ----------------
 web/static/js/inc/flot-charts/bar-chart.js         | 103 ---
 web/static/js/inc/flot-charts/curved-line-chart.js |  88 --
 web/static/js/inc/flot-charts/dynamic-chart.js     | 107 ---
 web/static/js/inc/flot-charts/line-chart.js        | 123 ---
 web/static/js/inc/flot-charts/pie-chart.js         |  88 --
 web/static/js/inc/functions.js                     | 389 +++------
 24 files changed, 363 insertions(+), 2915 deletions(-)
 create mode 100644 .codeclimate.yml
 delete mode 100644 web/static/js/functions.js
 delete mode 100644 web/static/js/inc/flot-charts/bar-chart.js
 delete mode 100644 web/static/js/inc/flot-charts/curved-line-chart.js
 delete mode 100644 web/static/js/inc/flot-charts/dynamic-chart.js
 delete mode 100644 web/static/js/inc/flot-charts/line-chart.js
 delete mode 100644 web/static/js/inc/flot-charts/pie-chart.js

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [init : debug] ************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04"
}

TASK [init : Update apt] *******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could            not fetch updated apt files"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1
`

**Comment by mkody** [comment]
Well, that's odd. Could you try again?

**Comment by efsysefsys** [comment]
still doesn't work

**Comment by SlvrEagle23** [comment]
Can you try `git reset --hard && git pull`, then running `chmod a+x update.sh` and `update.sh` again? Might be an issue with the order of the updates.

**Comment by SlvrEagle23** [comment]
Actually, now that I look at your setup, it appears your DNS resolution might be having issues. That likely is an issue outside of AzuraCast itself, and relating to the DNS server itself or the repositories.

**Comment by SlvrEagle23** [comment]
@efsysefsys Any update on this issue?

**Comment by efsysefsys** [comment]
i destroy my droplet , create new with fresh ubuntu16 install fresh azuracast , all ok and now i try update.sh and now all ok.w8 more updates and i check again.

**Comment by SlvrEagle23** [comment]
Good to hear. Thank you for your testing help :)
