### ISSUE TITLE
Request for pause in influxdb install task

### ISSUE THREAD

**Issue by andbou** [SlvrEagle23/AzuraCast#59]
Hello,

I have installed Azuracast on an Odroid C2.
It's not a bug but a request for a modification.

Could you insert in util/ansible/roles/influxdb/tasks/main.yml

- name: Pause 15 seconds
  pause: seconds=15

between

- name: restart influxdb
  service: name=influxdb enabled=yes state=restarted
  when: influx_installed.changed

and

- name: Create 'stations' database
  influxdb_database:
    hostname: "localhost"
    database_name: "{{ item }}"
    state: present
  with_items:
    - 'stations'

Sometimes the create task begin before the finishing of the restart task.

Thanks in advance.

**Comment by SlvrEagle23** [comment]
@andbou I'm thinking this is likely the reason for a lot of install failures that happen around that time period. The old shell script included a pause in that section for the same reason; updating Ansible to apply it to the new deploy script as well.

**Comment by andbou** [comment]
influx_installed.changed instead of influxdb_installed.changed
