### ISSUE TITLE
Install error: Create Sessions DB

### ISSUE THREAD

**Issue by danbo** [SlvrEagle23/AzuraCast#61]
Ubuntu 16.04

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [init : debug] ************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04 (production)"
}

TASK [init : debug] ************************************************************
skipping: [localhost]

TASK [init : Update apt] *******************************************************
ok: [localhost]

TASK [init : Install system packages] ******************************************
changed: [localhost] => (item=[u'apt-transport-https', u'curl', u'wget', u'build-essential', u'python-software-properties', u'pwgen', u'whois', u'python-pip'])

TASK [init : Update pip components] ********************************************
changed: [localhost] => (item=pip)

TASK [git : Install Git] *******************************************************
ok: [localhost]

TASK [azuracast-radio : Install IceCast2 (14.04)] ******************************
skipping: [localhost]

TASK [azuracast-radio : Install IceCast2 (16.04)] ******************************
changed: [localhost]

TASK [azuracast-radio : Install LiquidSoap] ************************************
changed: [localhost] => (item=[u'liquidsoap', u'liquidsoap-plugin-all'])

TASK [azuracast-radio : Link Fallback Error MP3] *******************************
changed: [localhost]

TASK [azuracast-user : (Prod) Generate AzuraCast Password] *********************
changed: [localhost]

TASK [azuracast-user : Create Groups] ******************************************
ok: [localhost] => (item=www-data)
changed: [localhost] => (item=admin)

TASK [azuracast-user : Assign User Password] ***********************************
ok: [localhost]

TASK [azuracast-user : Create AzuraCast User] **********************************
changed: [localhost]

TASK [azuracast-user : Modify www-data User] ***********************************
changed: [localhost]

TASK [azuracast-user : (Dev) Modify vagrant User] ******************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Modify www-data User] *****************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Add azuracast User to vagrant Group] **************
skipping: [localhost]

TASK [azuracast-config : Use Default Configuration Files] **********************
changed: [localhost] => (item=db)
changed: [localhost] => (item=influx)
changed: [localhost] => (item=cache)

TASK [azuracast-config : Write current environment to file.] *******************
changed: [localhost]

TASK [azuracast-config : Touch .deploy_run file] *******************************
changed: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] *******************
changed: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Create System Folders] ********************************
changed: [localhost] => (item=/var/azuracast/www_tmp)
changed: [localhost] => (item=/var/azuracast/www_tmp/cache)
changed: [localhost] => (item=/var/azuracast/www_tmp/sessions)
changed: [localhost] => (item=/var/azuracast/www_tmp/proxies)
changed: [localhost] => (item=/var/azuracast/stations)

TASK [influxdb : Add InfluxDB repo file] ***************************************
changed: [localhost]

TASK [influxdb : Add InfluxDB repo key] ****************************************
changed: [localhost]

TASK [influxdb : Update apt cache] *********************************************
ok: [localhost]

TASK [influxdb : Install python-influxdb] **************************************
changed: [localhost] => (item=influxdb)

TASK [influxdb : Install InfluxDB] *********************************************
changed: [localhost] => (item=[u'influxdb'])

TASK [influxdb : restart influxdb] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: influxdb"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=24   changed=18   unreachable=0    failed=1

root@a9183a369017:/var/azuracast/www# ./install.sh
Checking for Ansible: install ok installed
Installing AzuraCast (Environment: production)

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [init : debug] ************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04 (production)"
}

TASK [init : debug] ************************************************************
skipping: [localhost]

TASK [init : Update apt] *******************************************************
ok: [localhost]

TASK [init : Install system packages] ******************************************
ok: [localhost] => (item=[u'apt-transport-https', u'curl', u'wget', u'build-essential', u'python-software-properties', u'pwgen', u'whois', u'python-pip'])

TASK [init : Update pip components] ********************************************
ok: [localhost] => (item=pip)

TASK [git : Install Git] *******************************************************
ok: [localhost]

TASK [azuracast-radio : Install IceCast2 (14.04)] ******************************
skipping: [localhost]

TASK [azuracast-radio : Install IceCast2 (16.04)] ******************************
ok: [localhost]

TASK [azuracast-radio : Install LiquidSoap] ************************************
ok: [localhost] => (item=[u'liquidsoap', u'liquidsoap-plugin-all'])

TASK [azuracast-radio : Link Fallback Error MP3] *******************************
ok: [localhost]

TASK [azuracast-user : (Prod) Generate AzuraCast Password] *********************
changed: [localhost]

TASK [azuracast-user : Create Groups] ******************************************
ok: [localhost] => (item=www-data)
ok: [localhost] => (item=admin)

TASK [azuracast-user : Assign User Password] ***********************************
ok: [localhost]

TASK [azuracast-user : Create AzuraCast User] **********************************
changed: [localhost]

TASK [azuracast-user : Modify www-data User] ***********************************
ok: [localhost]

TASK [azuracast-user : (Dev) Modify vagrant User] ******************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Modify www-data User] *****************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Add azuracast User to vagrant Group] **************
skipping: [localhost]

TASK [azuracast-config : Use Default Configuration Files] **********************
ok: [localhost] => (item=db)
ok: [localhost] => (item=influx)
ok: [localhost] => (item=cache)

TASK [azuracast-config : Write current environment to file.] *******************
ok: [localhost]

TASK [azuracast-config : Touch .deploy_run file] *******************************
changed: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] *******************
ok: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Create System Folders] ********************************
ok: [localhost] => (item=/var/azuracast/www_tmp)
ok: [localhost] => (item=/var/azuracast/www_tmp/cache)
ok: [localhost] => (item=/var/azuracast/www_tmp/sessions)
ok: [localhost] => (item=/var/azuracast/www_tmp/proxies)
ok: [localhost] => (item=/var/azuracast/stations)

TASK [influxdb : Add InfluxDB repo file] ***************************************
ok: [localhost]

TASK [influxdb : Add InfluxDB repo key] ****************************************
ok: [localhost]

TASK [influxdb : Update apt cache] *********************************************
skipping: [localhost]

TASK [influxdb : Install python-influxdb] **************************************
ok: [localhost] => (item=influxdb)

TASK [influxdb : Install InfluxDB] *********************************************
ok: [localhost] => (item=[u'influxdb'])

TASK [influxdb : restart influxdb] *********************************************
skipping: [localhost]

TASK [influxdb : Pause to allow InfluxDB to spin up] ***************************
skipping: [localhost]

TASK [influxdb : Create 'stations' database] ***********************************
failed: [localhost](item=stations) => {"failed": true, "item": "stations", "msg": "HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=SHOW+DATABASES&db=stations (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f50c1175c50>: Failed to establish a new connection: [Errno 111] Connection refused',))"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=23   changed=3    unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
Sorry for the delay in getting back to this one; I've been sick this week. :(

It seems like your installation of MySQL/MariaDB was likely complete before AzuraCast was installed. Can you tell me more about the environment in which you're installing it? Are you using a VPS that has a prebuilt "LAMP" stack or something similar?

The install.sh script can't access and modify MySQL/MariaDB without having some way to access its credentials. If you already have MySQL/MariaDB installed and it has a different password prior to running the install.sh script, you can create a new file at `/root/.my.cnf` with the following contents:

```
[client]
user=root
password=password
```

Then try to run the installer again, and it should work.

**Comment by SlvrEagle23** [comment]
Can you try again and let me know if the little update I pushed had any impact on the installer?

Unfortunately, InfluxDB seems to report that a restart has been successful several seconds before its databases are actually spun up and ready to receive data. This means we have to add in a very kludgy "pause" command in the script to allow InfluxDB the necessary time to "spin up", even though we don't know how much time that takes from device to device. Sometimes it's less than 5 seconds, sometimes (such as this case) more than 10.

**Comment by SlvrEagle23** [comment]
@danbo Just following up to see if you have been able to install AzuraCast without issues with the new, longer delay added.

**Comment by SlvrEagle23** [comment]
Closing this issue, as the time limit has been raised for InfluxDB and I haven't heard any further reports of issues at this point. We can always update it later if needed.

**Comment by danbo** [comment]
Tried the latest and I'm getting the same thing, but it stops earlier:

Installing AzuraCast (Environment: production)

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [init : debug] ************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04 x86_64 (production)"
}

TASK [init : debug] ************************************************************
skipping: [localhost]

TASK [init : Update apt] *******************************************************
changed: [localhost]

TASK [init : Install system packages] ******************************************
changed: [localhost] => (item=[u'apt-transport-https', u'curl', u'wget', u'tar', u'build-essential', u'python-software-properties', u'pwgen', u'whois', u'python-pip'])

TASK [init : Update pip components] ********************************************
changed: [localhost] => (item=pip)

TASK [git : Install Git] *******************************************************
ok: [localhost]

TASK [azuracast-user : (Prod) Generate AzuraCast Password] *********************
changed: [localhost]

TASK [azuracast-user : Create Groups] ******************************************
ok: [localhost] => (item=www-data)
changed: [localhost] => (item=admin)

TASK [azuracast-user : Assign User Password] ***********************************
ok: [localhost]

TASK [azuracast-user : Create AzuraCast User] **********************************
changed: [localhost]

TASK [azuracast-user : Modify www-data User] ***********************************
changed: [localhost]

TASK [azuracast-user : (Dev) Modify vagrant User] ******************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Modify www-data User] *****************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Add azuracast User to vagrant Group] **************
skipping: [localhost]

TASK [azuracast-config : Use Default Configuration Files] **********************
changed: [localhost] => (item=db)
changed: [localhost] => (item=influx)
changed: [localhost] => (item=cache)

TASK [azuracast-config : Write current environment to file.] *******************
changed: [localhost]

TASK [azuracast-config : Touch .deploy_run file] *******************************
changed: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] *******************
changed: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Create System Folders] ********************************
changed: [localhost] => (item=/var/azuracast/www_tmp)
changed: [localhost] => (item=/var/azuracast/www_tmp/cache)
changed: [localhost] => (item=/var/azuracast/www_tmp/sessions)
changed: [localhost] => (item=/var/azuracast/www_tmp/proxies)
changed: [localhost] => (item=/var/azuracast/stations)
changed: [localhost] => (item=/var/azuracast/servers)

TASK [azuracast-radio : Install IceCast2 (14.04)] ******************************
skipping: [localhost]

TASK [azuracast-radio : Install IceCast2 (16.04)] ******************************
changed: [localhost]

TASK [azuracast-radio : Link Fallback Error MP3] *******************************
changed: [localhost]

TASK [azuracast-radio : Remove problematic LiquidSoap plugins] *****************
ok: [localhost] => (item=[u'liquidsoap-plugin-all', u'liquidsoap-plugin-opus'])

TASK [azuracast-radio : Install LiquidSoap] ************************************
changed: [localhost] => (item=[u'liquidsoap', u'liquidsoap-plugin-ogg', u'liquidsoap-plugin-vorbis', u'liquidsoap-plugin-lame', u'liquidsoap-plugin-flac', u'liquidsoap-plugin-icecast'])

TASK [azuracast-radio : Download ShoutCast 2 (x86)] ****************************
skipping: [localhost]

TASK [azuracast-radio : Download ShoutCast 2 (x64)] ****************************
changed: [localhost]

TASK [azuracast-radio : Extract ShoutCast 2 Binary] ****************************
changed: [localhost]

TASK [influxdb : Add InfluxDB repo file] ***************************************
changed: [localhost]

TASK [influxdb : Add InfluxDB repo key] ****************************************
changed: [localhost]

TASK [influxdb : Update apt cache] *********************************************
changed: [localhost]

TASK [influxdb : Install python-influxdb] **************************************
changed: [localhost] => (item=influxdb)

TASK [influxdb : Install InfluxDB] *********************************************
changed: [localhost] => (item=[u'influxdb'])

TASK [influxdb : restart influxdb] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: influxdb"}

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=27   changed=22   unreachable=0    failed=1

The command '/bin/sh -c ./install.sh' returned a non-zero code: 2

**Comment by danbo** [comment]
If I run the installer a second time, it skips the restart influxdb task and fails trying to connect:

```
TASK [influxdb : restart influxdb] *********************************************
skipping: [localhost]

TASK [influxdb : Pause to allow InfluxDB to spin up] ***************************
skipping: [localhost]

TASK [influxdb : Create 'stations' database] ***********************************
failed: [localhost] (item=stations) => {"failed": true, "item": "stations", "msg": "HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=SHOW+DATABASES&db=stations (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff2cc7fd850>: Failed to establish a new connection: [Errno 111] Connection refused',))"}

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=25   changed=4    unreachable=0    failed=1

```

**Comment by SlvrEagle23** [comment]
@danbo Influx has been a source of much headache for me, as the service responds that it is up and running several seconds before it's actually available to accept requests, and this makes spinning it up in Ansible a real mess.

In this case, you may need to manually execute `sudo service influxdb restart` and then run the installer again.

**Comment by danbo** [comment]
```
# sudo service influxdb restart
influxdb: unrecognized service
```

I'm no expert in init.d/upstart/systemd but it looks like the service doesn't "exist".

I see a /lib/systemd/system/influxdb.service file but I don't know how to invoke it.

**Comment by SlvrEagle23** [comment]
@danbo Sorry, didn't realize this issue was marked as closed, reopening it so it stays on the radar.

Can you try `sudo systemctl enable influxdb`? It may just need to be enabled...it's been reported that this is a known weirdness on influx's part.

**Comment by danbo** [comment]
I've come full circle. I neglected to mention what now appears quite relevant. I'm trying to run this in an Ubuntu 16.04 docker container. I learned that since the docker patterns prefer fit for purpose containers, they tuned out systemd from the ubuntu base images.

I'll have to grab a docker friendly image to play with assuming you have one.

**Comment by SlvrEagle23** [comment]
@danbo Oh, yes that is highly relevant!

All of my local development is done via Vagrant and standalone VMs, rather than Docker, so I don't actually have any Docker-friendly setup for AzuraCast at the moment. If someone wanted to pull-request one I would be happy to look at it and test it out, but I'm short on the time (and knowledge of Docker) needed to put one together myself from scratch.

**Comment by xogium** [comment]
Hi,
I ran into that with docker also. But as I found out, if you are on a linux system that use systemd already, you can use systemd-nspawn to run a full ubuntu 16.04 system (I run azuracast like this myself). The host is archlinux while the container is ubuntu 16.04. It worked out perfectly for me, except I had to modify the basic source.list file in /etc/apt to proivde other things than only main repo (backports, security, multiverse...). No warning, no installation failing first shot. The only issue I have so far is restarting the station via the web, it fails (I'll probably open an issue about this). Other than that, you'll have to enable the supervisor service at boot with
# systemctl enable supervisor

For getting started with systemd-nspawn, I recomment the excellent article on the arch wiki:
https://wiki.archlinux.org/index.php/Systemd-nspawn
Good luck !
