### ISSUE TITLE
TASK [mariadb : MySQL Root Account Fix (Ubuntu 16.04)]

### ISSUE THREAD

**Issue by AmericanSprite** [SlvrEagle23/AzuraCast#62]
Ubuntu 16.04.1

root@ubuntu:~# cd /var/azuracast/www
root@ubuntu:/var/azuracast/www# sudo ./install.sh
Checking for Ansible: install ok installed
Installing AzuraCast (Environment: production)

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [init : debug] ************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04 (production)"
}

TASK [init : debug] ************************************************************
skipping: [localhost]

TASK [init : Update apt] *******************************************************
ok: [localhost]

TASK [init : Install system packages] ******************************************
ok: [localhost] => (item=[u'apt-transport-https', u'curl', u'wget', u'build-essential', u'python-software-properties', u'pwgen', u'whois', u'python-pip'])

TASK [init : Update pip components] ********************************************
ok: [localhost] => (item=pip)

TASK [git : Install Git] *******************************************************
ok: [localhost]

TASK [azuracast-radio : Install IceCast2 (14.04)] ******************************
skipping: [localhost]

TASK [azuracast-radio : Install IceCast2 (16.04)] ******************************
ok: [localhost]

TASK [azuracast-radio : Install LiquidSoap] ************************************
ok: [localhost] => (item=[u'liquidsoap', u'liquidsoap-plugin-all'])

TASK [azuracast-radio : Link Fallback Error MP3] *******************************
ok: [localhost]

TASK [azuracast-user : (Prod) Generate AzuraCast Password] *********************
changed: [localhost]

TASK [azuracast-user : Create Groups] ******************************************
ok: [localhost] => (item=www-data)
ok: [localhost] => (item=admin)

TASK [azuracast-user : Assign User Password] ***********************************
ok: [localhost]

TASK [azuracast-user : Create AzuraCast User] **********************************
changed: [localhost]

TASK [azuracast-user : Modify www-data User] ***********************************
ok: [localhost]

TASK [azuracast-user : (Dev) Modify vagrant User] ******************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Modify www-data User] *****************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Add azuracast User to vagrant Group] **************
skipping: [localhost]

TASK [azuracast-config : Use Default Configuration Files] **********************
ok: [localhost] => (item=db)
ok: [localhost] => (item=influx)
ok: [localhost] => (item=cache)

TASK [azuracast-config : Write current environment to file.] *******************
ok: [localhost]

TASK [azuracast-config : Touch .deploy_run file] *******************************
changed: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] *******************
ok: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Create System Folders] ********************************
ok: [localhost] => (item=/var/azuracast/www_tmp)
ok: [localhost] => (item=/var/azuracast/www_tmp/cache)
ok: [localhost] => (item=/var/azuracast/www_tmp/sessions)
ok: [localhost] => (item=/var/azuracast/www_tmp/proxies)
ok: [localhost] => (item=/var/azuracast/stations)

TASK [influxdb : Add InfluxDB repo file] ***************************************
ok: [localhost]

TASK [influxdb : Add InfluxDB repo key] ****************************************
ok: [localhost]

TASK [influxdb : Update apt cache] *********************************************
skipping: [localhost]

TASK [influxdb : Install python-influxdb] **************************************
ok: [localhost] => (item=influxdb)

TASK [influxdb : Install InfluxDB] *********************************************
ok: [localhost] => (item=[u'influxdb'])

TASK [influxdb : restart influxdb] *********************************************
skipping: [localhost]

TASK [influxdb : Pause to allow InfluxDB to spin up] ***************************
skipping: [localhost]

TASK [influxdb : Create 'stations' database] ***********************************
ok: [localhost] => (item=stations)

TASK [influxdb : Create 'stations' retention policies] *************************
ok: [localhost] => (item={u'duration': u'5d', u'default': True, u'name': u'15s'})
ok: [localhost] => (item={u'duration': u'2w', u'default': False, u'name': u'1h'})
ok: [localhost] => (item={u'duration': u'INF', u'default': False, u'name': u'1d'})

TASK [influxdb : Manage continuous queries on 'stations'] **********************
changed: [localhost]

TASK [influxdb : Lock down InfluxDB to localhost requests] *********************
ok: [localhost]

TASK [nginx : Install nginx] ***************************************************
ok: [localhost]

TASK [nginx : Change default nginx site] ***************************************
ok: [localhost]

TASK [nginx : Turn sendfile off on nginx for local development] ****************
skipping: [localhost]

TASK [php : Add PHP PPA repository] ********************************************
ok: [localhost]

TASK [php : Update apt again] **************************************************
skipping: [localhost]

TASK [php : Install PHP Libraries] *********************************************
ok: [localhost] => (item=[u'php7.0-fpm', u'php7.0-cli', u'php7.0-gd', u'php7.0-curl', u'php7.0-xml', u'php7.0-zip', u'php7.0-mysqlnd', u'php7.0-mbstring', u'php7.0-intl'])

TASK [php : List locales] ******************************************************
changed: [localhost]

TASK [php : Create Locales] ****************************************************
ok: [localhost] => (item=de_DE.UTF-8)
ok: [localhost] => (item=es_ES.UTF-8)
ok: [localhost] => (item=fr_FR.UTF-8)
ok: [localhost] => (item=ru_RU.UTF-8)

TASK [php : Remove Old PHP Libraries] ******************************************
ok: [localhost] => (item=[u'php5-common', u'php5-fpm', u'php5-cli', u'php5-phalcon', u'php7.0-phalcon'])

TASK [php : Configure PHP FPM Pool] ********************************************
ok: [localhost]

TASK [php : Configure php-fpm php.ini] *****************************************
ok: [localhost] => (item={u'option': u'post_max_size', u'value': u'50M'})
ok: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})
ok: [localhost] => (item={u'option': u'upload_max_filesize', u'value': u'25M'})

TASK [php : Configure php-cli php.ini] *****************************************
ok: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})

TASK [mariadb : (Prod) Generate MySQL Root Password] ***************************
changed: [localhost]

TASK [mariadb : Assign User Password] ******************************************
ok: [localhost]

TASK [mariadb : Add repo file] *************************************************
skipping: [localhost]

TASK [mariadb : Add repo key] **************************************************
skipping: [localhost]

TASK [mariadb : Update apt cache] **********************************************
skipping: [localhost]

TASK [mariadb : Unattended package installation] *******************************
ok: [localhost]

TASK [mariadb : Install MariaDB] ***********************************************
ok: [localhost] => (item=[u'mariadb-server', u'mariadb-client'])

TASK [mariadb : Add configuration] *********************************************
ok: [localhost]

TASK [mariadb : Start and enable service] **************************************
ok: [localhost]

TASK [mariadb : MySQL Root Account Fix (Ubuntu 16.04)] *************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "cat /var/azuracast/www/util/xenial_mysql_fix.sql | mysql", "delta": "0:00:00.005531", "end": "2016-10-29 13:15:43.467724", "failed": true, "rc": 1, "start": "2016-10-29 13:15:43.462193", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [azuracast-user : send user notification] **********************
    to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=43   changed=6    unreachable=0    failed=1   

root@ubuntu:/var/azuracast/www#

**Comment by SlvrEagle23** [comment]
Sorry for the delay in getting back to this one; I've been sick this week. :(

It seems like your installation of MySQL/MariaDB was likely complete before AzuraCast was installed. Can you tell me more about the environment in which you're installing it? Are you using a VPS that has a prebuilt "LAMP" stack or something similar?

The install.sh script can't access and modify MySQL/MariaDB without having some way to access its credentials. If you already have MySQL/MariaDB installed and it has a different password prior to running the install.sh script, you can create a new file at `/root/.my.cnf` with the following contents:

```
[client]
user=root
password=password
```

Then try to run the installer again, and it should work.

**Comment by stephanzett** [comment]
Hi. 
Unfortunally this is not working. i got the same error again and again. i already reset the mysql root accounts password. (with this guid: https://help.ubuntu.com/community/MysqlPasswordReset) but still the same error. i created the correct .my.cnf file under /root/ with the correct pass in it. so what can i do?

**Comment by SlvrEagle23** [comment]
Can you tell me more about the environment you're running AzuraCast in? Is this a VPS provider, and if so, which one?

Apparently the environment in which I've been testing Ubuntu 16.04 is different from yours. If there is any way to provision a VPS in your environment *without* MariaDB/MySQL installed beforehand, that would likely lead to successful installation.

**Comment by adwidianjaya** [comment]
Hi, I face the same problem just now. However in my case, I use a machine with Ubuntu 16.04 installed. install.sh stopped when try to fix some permission or root stuff because of it fallback to default root password, which is 'NO'. In my case mariadb creates random password, which can be found in /root/.my.cnf. I just log into mariadb by using the random password, and finally I change the root password to "" (you may follow the steps provided in http://stackoverflow.com/questions/2101694/mysql-how-to-set-root-password-to-null). Then, I re-run install.sh, and it's finally worked! Hope help you guys. Thank you.

**Comment by SlvrEagle23** [comment]
Hey everyone, could you help me test out the prospective fix I pushed for this issue? It seems numerous people are having it, and it's caused by some sources of MariaDB on Ubuntu 16.04 preconfiguring a root password and some sources not doing this.
