### ISSUE TITLE
Upload and Refresh failure when Media Manager folder names are created with spaces

### ISSUE THREAD

**Issue by shaundewberry** [SlvrEagle23/AzuraCast#63]
In the Media Manager, if a folder is created with a space in the folder name, the folder does get created on the filesystem, but any attempt to view the contents of the folder hangs with the "Loading" message. 
A refresh at this time also fails. Refreshing the entire page makes no difference - it remains in "Loading". 
An attempt to upload a file to the folder shows the file(s) uploading, but the files are never placed in the folder on the underlying filesystem, and are not visible through the media manager interface.
Removal of any space characters corrects this issue.

(Also, any possibility of entire folder uploads in future? ;-) )

**Comment by SlvrEagle23** [comment]
@shaundewberry The push I just made should fix the issue with spaces in the folders, as it seems that this was a browser-specific issue with some browsers sending the encoded hash (i.e. with %20) and others sending a fully decoded version already. Always decoding the component seems to resolve the issue.

As for your second question, it is possible to allow bulk folder uploading via a drag-and-drop file upload mechanism, but support for it is shaky between browsers. I would love to implement it once support gets a little more stable across the board.

**Comment by shaundewberry** [comment]
Tested and working beautifully. Thank you.
