### ISSUE TITLE
Role created but no Permissions assignable.

### ISSUE THREAD

**Issue by shaundewberry** [SlvrEagle23/AzuraCast#64]
When assigning permissions to a Role, no permissions are visible or selectable.
See screenshot.
![azuracast permissions](https://cloud.githubusercontent.com/assets/11535885/20177213/4bd39a1c-a754-11e6-860d-991393cf742f.PNG)
Tested on latest Firefox and Chrome.

**Comment by SlvrEagle23** [comment]
@shaundewberry Nice catch. Not sure how I had missed that one actually. Case-sensitive issue would've always happened for all Linux instances, but not if you're using Vagrant with a Windows directory mounted (as it mounts as case-insensitive).

**Comment by shaundewberry** [comment]
Thanks for the fix.
