### ISSUE TITLE
failed downloading icecast on install

### ISSUE THREAD

**Issue by johnEcash** [SlvrEagle23/AzuraCast#65]
when trying to run install.sh I get following error:

`TASK [azuracast-radio : Install IceCast2 (14.04)] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading http://download.opensuse.org/repositories/multimedia:/xiph/xUbuntu_14.04/amd64/icecast2_2.4.2-2_amd64.deb, 'NoneType' object has no attribute 'read'"}
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry
`

**Comment by SlvrEagle23** [comment]
@johnEcash We're seeing the same issue on our CI build machine with 14.04. Installation should work without any issues on 16.04, but I'll look into what's causing the 404 on the IceCast deb package for 14.04.

**Comment by SlvrEagle23** [comment]
@johnEcash Commit c7a7a23 updates the repo to a URL that is still currently up and running. Pull down an updated version of the repo (`git reset --HARD && git pull`) and it should work fine.
