### ISSUE TITLE
Radio Backend: No PID file found

### ISSUE THREAD

**Issue by adwidianjaya** [SlvrEagle23/AzuraCast#70]
Hello, what a great project AzuraCast, I really apreciated. However, in my first trial using AzuraCast I found some problems. AzuraCast couldn't connect to icecast2 since there is no mountpoint appeared in icecast2 administrator page. When I try to use utilities you provided (Restart Broadcasting), I got this error messages. Any idea? Thank you

![screen shot 2016-11-20 at 19 05 44](https://cloud.githubusercontent.com/assets/5211073/20462603/c6e0ecde-af54-11e6-8a78-0011b510c9fd.png)

**Comment by SlvrEagle23** [comment]
@adwidianjaya Thank you for trying out AzuraCast :D

These messages are normal until you have added songs and playlists. LiquidSoap (the AutoDJ) won't run without anything to play.

Make sure you have at least one song in a playlist, and at least one playlist that is "standard" (always running), and then try restarting broadcasting again.

**Comment by adwidianjaya** [comment]
Wow, it actually worked! Thank you so much @SlvrEagle23 👍 

Just a suggestion, you may provide guide or message in notification to have the user create his/her first playlist with at least one song.
And also, I have one more question. I've successfully make <server-ip>:8000/radio.mp3 play my songs in the playlist. But however, when I tried to visit public page, I got this view. There was no song title, nor the artist. Did I miss something?

![screen shot 2016-11-21 at 10 44 00](https://cloud.githubusercontent.com/assets/5211073/20470079/be72190a-afd7-11e6-8da1-8c0915009b74.png)
