### ISSUE TITLE
problem with supervisord

### ISSUE THREAD

**Issue by andbou** [SlvrEagle23/AzuraCast#77]
Just a request if its possible.
I have updated the station table in my db and now for this station "radio_base_dir" point to /media/sdcard (sdcard mounted in my odroid c2).
In /util/ansible/roles/supervisord/templates/supervisord.conf.j2 the last line is not compatible with my change.
I made this replacement :
	files = /media/sdcard/config/supervisord.conf
Have you a permanent solution.

Thank you in advance.

**Comment by SlvrEagle23** [comment]
@andbou The easy solution here is to create a symlink from your station folder to a folder inside `/var/azuracast/stations`. A similar command would be:

`ln -s /media/sdcard /var/azuracast/stations/station_name`

Supervisord (and all other relevant scripts) should properly follow that symlink. If you run into any issues with this method, let me know. :)

**Comment by andbou** [comment]
It works fine for me.
Thanks for your support.
Excellent job.
