### ISSUE TITLE
Remote Volumes using SSHFS

### ISSUE THREAD

**Issue by EpicnessTwo** [SlvrEagle23/AzuraCast#78]
Is it possible for this system to support remote volumes using sshfs? I have this hosted on it's own VPS but all my music is stored on another.

**Comment by SlvrEagle23** [comment]
@EpicnessTwo By all means, it should be possible to mount `/var/azuracast/stations` on a remote drive (i.e. SSHFS), though you may incur some performance problems by doing this.

Let me know if you have any questions.

**Comment by SlvrEagle23** [comment]
@EpicnessTwo I don't really have a local SSHFS setup to test that against, but it seems like it's incorrectly mounting as a file rather than a folder. If you actually SSH into the filesystem and type `ls -lah` in the parent folder, what does it say?

**Comment by SlvrEagle23** [comment]
Closing as unsupported for now, as I also can't guarantee that the underlying radio broadcast and playlist software all support pointing to filesystems that are mounted via SSHFS.

**Comment by griffon56** [comment]
I have exactly the same issue as above, the folder is shown as 'not processed' and 'null bytes' when mounted with SSHFS. Here is the result of `ls -lah`
![image](https://cloud.githubusercontent.com/assets/25333002/25408908/176cab1c-2a10-11e7-9c3b-927a28544cfd.png)
![image](https://cloud.githubusercontent.com/assets/25333002/25408935/375816f0-2a10-11e7-9677-6232ab2ec2e9.png)

**Comment by mkody** [comment]
@griffon56 As told before, SSHFS is unsupported.  
Plus, the latency and CPU usage could be a big problem as we're  accessing files continuously.
