### ISSUE TITLE
Fatal: Localhost - Failed to connect to localhost

### ISSUE THREAD

**Issue by kbysfm** [SlvrEagle23/AzuraCast#82]
I'm relatively new at programming, any help would be great!

The azuracast install is running on Ubuntu 16.0.4 LTS. I'm able to connect and view azuracast gui, however I can't view the profile page or restart broadcast without seeing an exception error.

This fatal error occurs after running ./update

`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php radio:restart", "delta": "0:00:00.159977", "end": "2017-01-12 09:01:07.845663", "failed": true, "rc": 1, "start": "2017-01-12 09:01:07.685686", "stderr": "\n                                                                               \n  [fXmlRpc\\Exception\\TransportException]                                       \n  Transport error occurred: cURL error 7: Failed to connect to 127.0.0.1 port  \n   9001: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors  \n  .html)                                                                       \n                                                                               \n\n                                                                               \n  [Http\\Client\\Exception\\NetworkException]                                     \n  cURL error 7: Failed to connect to 127.0.0.1 port 9001: Connection refused   \n  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                      \n                                                                               \n\n                                                                               \n  [GuzzleHttp\\Exception\\ConnectException]                                      \n  cURL error 7: Failed to connect to 127.0.0.1 port 9001: Connection refused   \n  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                      \n                                                                               \n\nradio:restart", "stdout": "Restarting all radio stations...\n---------------------------------------------", "stdout_lines": ["Restarting all radio stations...", "---------------------------------------------"], "warnings": []}`

Thanks!

**Comment by SlvrEagle23** [comment]
@kbysfm That sounds like supervisord failed to start. Can you log in to the server's SSH shell and execute `sudo service supervisor restart`?

**Comment by kbysfm** [comment]
That seemed to have done the trick. Thanks @SlvrEagle23. Last (outside of this issue) question. How do you manually remove a station? For some reason when I try to delete a station I get this exception error
> fXmlRpc \ Exception \ FaultException
HELP
BAD_NAME: station_4:station_4_backend

**Comment by Roforum** [comment]
the solution for me was to run again ./install.sh and without losing anything. I had everything the same.
