### ISSUE TITLE
ERROR: become is not a legal parameter at this level in an Ansible Playbook

### ISSUE THREAD

**Issue by thunderclap76** [SlvrEagle23/AzuraCast#87]
Installation could not continue due to the error.

**Comment by mkody** [comment]
Hi,
Could you tell us what version of Ansible you're running? Use `ansible --version` to check.
Also, is that the only thing you get when running `install.sh` or `update.sh`?

FYI, ansible 2.2.1.0 and 2.1.2.0 works for me.
