### ISSUE TITLE
Error on clicking "Apply pending changes"

### ISSUE THREAD

**Issue by QwiBeck** [SlvrEagle23/AzuraCast#93]
Transport error occurred: cURL error 7: Failed to connect to 127.0.0.1 port 9001: В соединении отказано (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by SlvrEagle23** [comment]
@QwiBeck This error usually means that supervisord failed to start on reboot. Log in to the server and type `sudo service supervisor restart` and it should fix it.

**Comment by andbou** [comment]
@QwiBeck This error usually means that supervisord failed to start on reboot. Log in to the server and type sudo service supervisor restart and it should fix it.

FYI: For me, "update-rc.d supervisor enable" was also needed.
