### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by RainbowDash53** [SlvrEagle23/AzuraCast#97]
I've got an error on the install of Azura:
TASK [mariadb : Remove test database and access to it] *************************
failed: [localhost] (item=DROP DATABASE test) => {"changed": false, "cmd": ["mysql", "--defaults-extra-file=/root/.my.cnf", "-ne", "DROP DATABASE test"], "delta": "0:00:00.010559", "end": "2017-03-09 18:40:36.749585", "failed": true, "item": "DROP DATABASE test", "rc": 1, "start": "2017-03-09 18:40:36.739026", "stderr": "ERROR 1008 (HY000) at line 1: Can't drop database 'test'; database doesn't exist", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by RainbowDash53** [comment]
I've try with: sudo ./install.sh

Now i've got:
TASK [mariadb : Set root Password] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: NO)\")"}

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=52   changed=8    unreachable=0    failed=1

**Comment by RainbowDash53** [comment]
Ok, now i don't have any error, but nothing on my server page:
http://185.163.126.38/

**Comment by Xe** [comment]
Did you install this on top of a completely fresh linux install?

**Comment by RainbowDash53** [comment]
> Did you install this on top of a completely fresh linux install?

Is now fonctionnal:
http://185.163.126.38/

But i can't restart my station or switch on LiquidSoap:
http://185.163.126.38/station/1/profile/backend/start
http://prntscr.com/ehzwcg

**Comment by Xe** [comment]
You didn't answer my question though. When you started was it with a completely blank server?

**Comment by RainbowDash53** [comment]
> You didn't answer my question though. When you started was it with a completely blank server?

No, i've apache preinstalled on my webserver, how it is possible ? How can i delete all the preinstalled software ?

**Comment by Xe** [comment]
> How can i delete all the preinstalled software?

Generally the best way to install Azuracast is to start from a completely blank and new server. Start with Ubuntu 16.04 **WITHOUT** any extra packages.

**Comment by colmrs** [comment]
Also please see my issue: 
https://github.com/SlvrEagle23/AzuraCast/issues/95

You have to run the install as a root user not just sudo
