### ISSUE TITLE
Recommendations to ameliorate your software

### ISSUE THREAD

**Issue by RainbowDash53** [SlvrEagle23/AzuraCast#98]
Hi to the developpers, i'm french guy, and I really like your system, but i've now to request from you:
An api to show the album cover art of a song(use Amazon, Spotify, or idk), voting system, and dedicace system directly in your panel

**Comment by RainbowDash53** [comment]
And why do you now open a plugin system to create custom things who we can share with the community

**Comment by SlvrEagle23** [comment]
@RainbowDash53 The enhancements you requested have been created as separate issues: #102 #103 #104
